let
    Source = Web.BrowserContents("https://fr.wikipedia.org/wiki/Liste_des_villes_et_agglom%C3%A9rations_les_plus_peupl%C3%A9es"),
    #"Table extraite à partir de code Html" = Html.Table(Source, {{"Column1", "TABLE.sticky-header-multi.sortable.wikitable > * > TR > TH[rowspan=""2""]:not([colspan]):nth-child(1):nth-last-child(7), TABLE.sticky-header-multi.sortable.wikitable > * > TR > TH:not([colspan]):not([rowspan]):nth-child(1):nth-last-child(11), TABLE.sticky-header-multi.sortable.wikitable > * > TR > TH:not([colspan]):not([rowspan]):nth-child(1):nth-last-child(10)"}, {"Column2", "TABLE.sticky-header-multi.sortable.wikitable > * > TR > TH[rowspan=""2""]:not([colspan]):nth-child(1):nth-last-child(7) + TH[rowspan=""2""]:not([colspan]):nth-child(2):nth-last-child(6), TABLE.sticky-header-multi.sortable.wikitable > * > TR > TH:not([colspan]):not([rowspan]):nth-child(1):nth-last-child(11) + TD:not([colspan]):not([rowspan]):nth-child(2):nth-last-child(10), TABLE.sticky-header-multi.sortable.wikitable > * > TR > TH:not([colspan]):not([rowspan]):nth-child(1):nth-last-child(10) + TD:not([colspan]):not([rowspan]):nth-child(2):nth-last-child(9)"}, {"Column3", "TABLE.sticky-header-multi.sortable.wikitable > * > TR > TH[rowspan=""2""]:not([colspan]):nth-child(1):nth-last-child(7) + TH[rowspan=""2""]:not([colspan]):nth-child(2):nth-last-child(6) + TH[rowspan=""2""]:not([colspan]):nth-child(3):nth-last-child(5), TABLE.sticky-header-multi.sortable.wikitable > * > TR > TH:not([colspan]):not([rowspan]):nth-child(1):nth-last-child(11) + TD:not([colspan]):not([rowspan]):nth-child(2):nth-last-child(10) + TD:not([colspan]):not([rowspan]):nth-child(3):nth-last-child(9), TABLE.sticky-header-multi.sortable.wikitable > * > TR > TH:not([colspan]):not([rowspan]):nth-child(1):nth-last-child(10) + TD:not([colspan]):not([rowspan]):nth-child(2):nth-last-child(9) + TD:not([colspan]):not([rowspan]):nth-child(3):nth-last-child(8)"}, {"Column4", "TABLE.sticky-header-multi.sortable.wikitable > * > TR > TH[rowspan=""2""]:not([colspan]):nth-child(1):nth-last-child(7) + TH[rowspan=""2""]:not([colspan]):nth-child(2):nth-last-child(6) + TH[rowspan=""2""]:not([colspan]):nth-child(3):nth-last-child(5) + TH[colspan=""3""]:not([rowspan]):nth-child(4):nth-last-child(4), TABLE.sticky-header-multi.sortable.wikitable > * > TR > TH:not([colspan]):not([rowspan]):nth-child(1):nth-last-child(8), TABLE.sticky-header-multi.sortable.wikitable > * > TR > TH:not([colspan]):not([rowspan]):nth-child(1):nth-last-child(11) + TD:not([colspan]):not([rowspan]):nth-child(2):nth-last-child(10) + TD:not([colspan]):not([rowspan]):nth-child(3):nth-last-child(9) + TD:not([colspan]):not([rowspan]):nth-child(4):nth-last-child(8), TABLE.sticky-header-multi.sortable.wikitable > * > TR > TH:not([colspan]):not([rowspan]):nth-child(1):nth-last-child(10) + TD:not([colspan]):not([rowspan]):nth-child(2):nth-last-child(9) + TD:not([colspan]):not([rowspan]):nth-child(3):nth-last-child(8) + TD:not([colspan]):not([rowspan]):nth-child(4):nth-last-child(7)"}, {"Column5", "TABLE.sticky-header-multi.sortable.wikitable > * > TR > TH[rowspan=""2""]:not([colspan]):nth-child(1):nth-last-child(7) + TH[rowspan=""2""]:not([colspan]):nth-child(2):nth-last-child(6) + TH[rowspan=""2""]:not([colspan]):nth-child(3):nth-last-child(5) + TH[colspan=""3""]:not([rowspan]):nth-child(4):nth-last-child(4), TABLE.sticky-header-multi.sortable.wikitable > * > TR > TH:not([colspan]):not([rowspan]):nth-child(1):nth-last-child(8) + TH:not([colspan]):not([rowspan]):nth-child(2):nth-last-child(7), TABLE.sticky-header-multi.sortable.wikitable > * > TR > TH:not([colspan]):not([rowspan]):nth-child(1):nth-last-child(11) + TD:not([colspan]):not([rowspan]):nth-child(2):nth-last-child(10) + TD:not([colspan]):not([rowspan]):nth-child(3):nth-last-child(9) + TD:not([colspan]):not([rowspan]):nth-child(4):nth-last-child(8) + TD:not([colspan]):not([rowspan]):nth-child(5):nth-last-child(7), TABLE.sticky-header-multi.sortable.wikitable > * > TR > TH:not([colspan]):not([rowspan]):nth-child(1):nth-last-child(10) + TD:not([colspan]):not([rowspan]):nth-child(2):nth-last-child(9) + TD:not([colspan]):not([rowspan]):nth-child(3):nth-last-child(8) + TD:not([colspan]):not([rowspan]):nth-child(4):nth-last-child(7) + TD:not([colspan]):not([rowspan]):nth-child(5):nth-last-child(6)"}, {"Column6", "TABLE.sticky-header-multi.sortable.wikitable > * > TR > TH[rowspan=""2""]:not([colspan]):nth-child(1):nth-last-child(7) + TH[rowspan=""2""]:not([colspan]):nth-child(2):nth-last-child(6) + TH[rowspan=""2""]:not([colspan]):nth-child(3):nth-last-child(5) + TH[colspan=""3""]:not([rowspan]):nth-child(4):nth-last-child(4), TABLE.sticky-header-multi.sortable.wikitable > * > TR > TH:not([colspan]):not([rowspan]):nth-child(1):nth-last-child(8) + TH:not([colspan]):not([rowspan]):nth-child(2):nth-last-child(7) + TH:not([colspan]):not([rowspan]):nth-child(3):nth-last-child(6), TABLE.sticky-header-multi.sortable.wikitable > * > TR > TH:not([colspan]):not([rowspan]):nth-child(1):nth-last-child(11) + TD:not([colspan]):not([rowspan]):nth-child(2):nth-last-child(10) + TD:not([colspan]):not([rowspan]):nth-child(3):nth-last-child(9) + TD:not([colspan]):not([rowspan]):nth-child(4):nth-last-child(8) + TD:not([colspan]):not([rowspan]):nth-child(5):nth-last-child(7) + TD:not([colspan]):not([rowspan]):nth-child(6):nth-last-child(6), TABLE.sticky-header-multi.sortable.wikitable > * > TR > TH:not([colspan]):not([rowspan]):nth-child(1):nth-last-child(10) + TD:not([colspan]):not([rowspan]):nth-child(2):nth-last-child(9) + TD:not([colspan]):not([rowspan]):nth-child(3):nth-last-child(8) + TD:not([colspan]):not([rowspan]):nth-child(4):nth-last-child(7) + TD:not([colspan]):not([rowspan]):nth-child(5):nth-last-child(6) + TD:not([colspan]):not([rowspan]):nth-child(6):nth-last-child(5)"}, {"Column7", "TABLE.sticky-header-multi.sortable.wikitable > * > TR > TH[rowspan=""2""]:not([colspan]):nth-child(1):nth-last-child(7) + TH[rowspan=""2""]:not([colspan]):nth-child(2):nth-last-child(6) + TH[rowspan=""2""]:not([colspan]):nth-child(3):nth-last-child(5) + TH[colspan=""3""]:not([rowspan]):nth-child(4):nth-last-child(4) + TH:not([colspan]):not([rowspan]):nth-child(5):nth-last-child(3), TABLE.sticky-header-multi.sortable.wikitable > * > TR > TH:not([colspan]):not([rowspan]):nth-child(1):nth-last-child(8) + TH:not([colspan]):not([rowspan]):nth-child(2):nth-last-child(7) + TH:not([colspan]):not([rowspan]):nth-child(3):nth-last-child(6) + TH:not([colspan]):not([rowspan]):nth-child(4):nth-last-child(5), TABLE.sticky-header-multi.sortable.wikitable > * > TR > TH:not([colspan]):not([rowspan]):nth-child(1):nth-last-child(11) + TD:not([colspan]):not([rowspan]):nth-child(2):nth-last-child(10) + TD:not([colspan]):not([rowspan]):nth-child(3):nth-last-child(9) + TD:not([colspan]):not([rowspan]):nth-child(4):nth-last-child(8) + TD:not([colspan]):not([rowspan]):nth-child(5):nth-last-child(7) + TD:not([colspan]):not([rowspan]):nth-child(6):nth-last-child(6) + TD:not([colspan]):not([rowspan]):nth-child(7):nth-last-child(5), TABLE.sticky-header-multi.sortable.wikitable > * > TR > TH:not([colspan]):not([rowspan]):nth-child(1):nth-last-child(10) + TD:not([colspan]):not([rowspan]):nth-child(2):nth-last-child(9) + TD:not([colspan]):not([rowspan]):nth-child(3):nth-last-child(8) + TD:not([colspan]):not([rowspan]):nth-child(4):nth-last-child(7) + TD:not([colspan]):not([rowspan]):nth-child(5):nth-last-child(6) + TD:not([colspan]):not([rowspan]):nth-child(6):nth-last-child(5) + TD:not([colspan]):not([rowspan]):nth-child(7):nth-last-child(4)"}, {"Column8", "TABLE.sticky-header-multi.sortable.wikitable > * > TR > TH[rowspan=""2""]:not([colspan]):nth-child(1):nth-last-child(7) + TH[rowspan=""2""]:not([colspan]):nth-child(2):nth-last-child(6) + TH[rowspan=""2""]:not([colspan]):nth-child(3):nth-last-child(5) + TH[colspan=""3""]:not([rowspan]):nth-child(4):nth-last-child(4) + TH:not([colspan]):not([rowspan]):nth-child(5):nth-last-child(3) + TH[colspan=""2""]:not([rowspan]):nth-child(6):nth-last-child(2), TABLE.sticky-header-multi.sortable.wikitable > * > TR > TH:not([colspan]):not([rowspan]):nth-child(1):nth-last-child(8) + TH:not([colspan]):not([rowspan]):nth-child(2):nth-last-child(7) + TH:not([colspan]):not([rowspan]):nth-child(3):nth-last-child(6) + TH:not([colspan]):not([rowspan]):nth-child(4):nth-last-child(5) + TH:not([colspan]):not([rowspan]):nth-child(5):nth-last-child(4), TABLE.sticky-header-multi.sortable.wikitable > * > TR > TH:not([colspan]):not([rowspan]):nth-child(1):nth-last-child(11) + TD:not([colspan]):not([rowspan]):nth-child(2):nth-last-child(10) + TD:not([colspan]):not([rowspan]):nth-child(3):nth-last-child(9) + TD:not([colspan]):not([rowspan]):nth-child(4):nth-last-child(8) + TD:not([colspan]):not([rowspan]):nth-child(5):nth-last-child(7) + TD:not([colspan]):not([rowspan]):nth-child(6):nth-last-child(6) + TD:not([colspan]):not([rowspan]):nth-child(7):nth-last-child(5) + TD:not([colspan]):not([rowspan]):nth-child(8):nth-last-child(4), TABLE.sticky-header-multi.sortable.wikitable > * > TR > TH:not([colspan]):not([rowspan]):nth-child(1):nth-last-child(10) + TD:not([colspan]):not([rowspan]):nth-child(2):nth-last-child(9) + TD:not([colspan]):not([rowspan]):nth-child(3):nth-last-child(8) + TD:not([colspan]):not([rowspan]):nth-child(4):nth-last-child(7) + TD:not([colspan]):not([rowspan]):nth-child(5):nth-last-child(6) + TD:not([colspan]):not([rowspan]):nth-child(6):nth-last-child(5) + TD:not([colspan]):not([rowspan]):nth-child(7):nth-last-child(4) + TD:not([colspan]):not([rowspan]):nth-child(8):nth-last-child(3)"}, {"Column9", "TABLE.sticky-header-multi.sortable.wikitable > * > TR > TH[rowspan=""2""]:not([colspan]):nth-child(1):nth-last-child(7) + TH[rowspan=""2""]:not([colspan]):nth-child(2):nth-last-child(6) + TH[rowspan=""2""]:not([colspan]):nth-child(3):nth-last-child(5) + TH[colspan=""3""]:not([rowspan]):nth-child(4):nth-last-child(4) + TH:not([colspan]):not([rowspan]):nth-child(5):nth-last-child(3) + TH[colspan=""2""]:not([rowspan]):nth-child(6):nth-last-child(2), TABLE.sticky-header-multi.sortable.wikitable > * > TR > TH:not([colspan]):not([rowspan]):nth-child(1):nth-last-child(8) + TH:not([colspan]):not([rowspan]):nth-child(2):nth-last-child(7) + TH:not([colspan]):not([rowspan]):nth-child(3):nth-last-child(6) + TH:not([colspan]):not([rowspan]):nth-child(4):nth-last-child(5) + TH:not([colspan]):not([rowspan]):nth-child(5):nth-last-child(4) + TH:not([colspan]):not([rowspan]):nth-child(6):nth-last-child(3), TABLE.sticky-header-multi.sortable.wikitable > * > TR > TH:not([colspan]):not([rowspan]):nth-child(1):nth-last-child(11) + TD:not([colspan]):not([rowspan]):nth-child(2):nth-last-child(10) + TD:not([colspan]):not([rowspan]):nth-child(3):nth-last-child(9) + TD:not([colspan]):not([rowspan]):nth-child(4):nth-last-child(8) + TD:not([colspan]):not([rowspan]):nth-child(5):nth-last-child(7) + TD:not([colspan]):not([rowspan]):nth-child(6):nth-last-child(6) + TD:not([colspan]):not([rowspan]):nth-child(7):nth-last-child(5) + TD:not([colspan]):not([rowspan]):nth-child(8):nth-last-child(4) + TD:not([colspan]):not([rowspan]):nth-child(9):nth-last-child(3), TABLE.sticky-header-multi.sortable.wikitable > * > TR > TH:not([colspan]):not([rowspan]):nth-child(1):nth-last-child(10) + TD:not([colspan]):not([rowspan]):nth-child(2):nth-last-child(9) + TD:not([colspan]):not([rowspan]):nth-child(3):nth-last-child(8) + TD:not([colspan]):not([rowspan]):nth-child(4):nth-last-child(7) + TD:not([colspan]):not([rowspan]):nth-child(5):nth-last-child(6) + TD:not([colspan]):not([rowspan]):nth-child(6):nth-last-child(5) + TD:not([colspan]):not([rowspan]):nth-child(7):nth-last-child(4) + TD:not([colspan]):not([rowspan]):nth-child(8):nth-last-child(3) + TD:not([colspan]):not([rowspan]):nth-child(9):nth-last-child(2)"}, {"Column10", "TABLE.sticky-header-multi.sortable.wikitable > * > TR > TH[rowspan=""2""]:not([colspan]):nth-child(1):nth-last-child(7) + TH[rowspan=""2""]:not([colspan]):nth-child(2):nth-last-child(6) + TH[rowspan=""2""]:not([colspan]):nth-child(3):nth-last-child(5) + TH[colspan=""3""]:not([rowspan]):nth-child(4):nth-last-child(4) + TH:not([colspan]):not([rowspan]):nth-child(5):nth-last-child(3) + TH[colspan=""2""]:not([rowspan]):nth-child(6):nth-last-child(2) + TH[colspan=""2""]:not([rowspan]):nth-child(7):nth-last-child(1), TABLE.sticky-header-multi.sortable.wikitable > * > TR > TH:not([colspan]):not([rowspan]):nth-child(1):nth-last-child(8) + TH:not([colspan]):not([rowspan]):nth-child(2):nth-last-child(7) + TH:not([colspan]):not([rowspan]):nth-child(3):nth-last-child(6) + TH:not([colspan]):not([rowspan]):nth-child(4):nth-last-child(5) + TH:not([colspan]):not([rowspan]):nth-child(5):nth-last-child(4) + TH:not([colspan]):not([rowspan]):nth-child(6):nth-last-child(3) + TH:not([colspan]):not([rowspan]):nth-child(7):nth-last-child(2), TABLE.sticky-header-multi.sortable.wikitable > * > TR > TH:not([colspan]):not([rowspan]):nth-child(1):nth-last-child(11) + TD:not([colspan]):not([rowspan]):nth-child(2):nth-last-child(10) + TD:not([colspan]):not([rowspan]):nth-child(3):nth-last-child(9) + TD:not([colspan]):not([rowspan]):nth-child(4):nth-last-child(8) + TD:not([colspan]):not([rowspan]):nth-child(5):nth-last-child(7) + TD:not([colspan]):not([rowspan]):nth-child(6):nth-last-child(6) + TD:not([colspan]):not([rowspan]):nth-child(7):nth-last-child(5) + TD:not([colspan]):not([rowspan]):nth-child(8):nth-last-child(4) + TD:not([colspan]):not([rowspan]):nth-child(9):nth-last-child(3) + TD:not([colspan]):not([rowspan]):nth-child(10):nth-last-child(2), TABLE.sticky-header-multi.sortable.wikitable > * > TR > TH:not([colspan]):not([rowspan]):nth-child(1):nth-last-child(10) + TD:not([colspan]):not([rowspan]):nth-child(2):nth-last-child(9) + TD:not([colspan]):not([rowspan]):nth-child(3):nth-last-child(8) + TD:not([colspan]):not([rowspan]):nth-child(4):nth-last-child(7) + TD:not([colspan]):not([rowspan]):nth-child(5):nth-last-child(6) + TD:not([colspan]):not([rowspan]):nth-child(6):nth-last-child(5) + TD:not([colspan]):not([rowspan]):nth-child(7):nth-last-child(4) + TD:not([colspan]):not([rowspan]):nth-child(8):nth-last-child(3) + TD:not([colspan]):not([rowspan]):nth-child(9):nth-last-child(2) + TD:not([colspan]):not([rowspan]):nth-child(10):nth-last-child(1)"}, {"Column11", "TABLE.sticky-header-multi.sortable.wikitable > * > TR > TH[rowspan=""2""]:not([colspan]):nth-child(1):nth-last-child(7) + TH[rowspan=""2""]:not([colspan]):nth-child(2):nth-last-child(6) + TH[rowspan=""2""]:not([colspan]):nth-child(3):nth-last-child(5) + TH[colspan=""3""]:not([rowspan]):nth-child(4):nth-last-child(4) + TH:not([colspan]):not([rowspan]):nth-child(5):nth-last-child(3) + TH[colspan=""2""]:not([rowspan]):nth-child(6):nth-last-child(2) + TH[colspan=""2""]:not([rowspan]):nth-child(7):nth-last-child(1), TABLE.sticky-header-multi.sortable.wikitable > * > TR > TH:not([colspan]):not([rowspan]):nth-child(1):nth-last-child(8) + TH:not([colspan]):not([rowspan]):nth-child(2):nth-last-child(7) + TH:not([colspan]):not([rowspan]):nth-child(3):nth-last-child(6) + TH:not([colspan]):not([rowspan]):nth-child(4):nth-last-child(5) + TH:not([colspan]):not([rowspan]):nth-child(5):nth-last-child(4) + TH:not([colspan]):not([rowspan]):nth-child(6):nth-last-child(3) + TH:not([colspan]):not([rowspan]):nth-child(7):nth-last-child(2) + TH:not([colspan]):not([rowspan]):nth-child(8):nth-last-child(1), TABLE.sticky-header-multi.sortable.wikitable > * > TR > TH:not([colspan]):not([rowspan]):nth-child(1):nth-last-child(11) + TD:not([colspan]):not([rowspan]):nth-child(2):nth-last-child(10) + TD:not([colspan]):not([rowspan]):nth-child(3):nth-last-child(9) + TD:not([colspan]):not([rowspan]):nth-child(4):nth-last-child(8) + TD:not([colspan]):not([rowspan]):nth-child(5):nth-last-child(7) + TD:not([colspan]):not([rowspan]):nth-child(6):nth-last-child(6) + TD:not([colspan]):not([rowspan]):nth-child(7):nth-last-child(5) + TD:not([colspan]):not([rowspan]):nth-child(8):nth-last-child(4) + TD:not([colspan]):not([rowspan]):nth-child(9):nth-last-child(3) + TD:not([colspan]):not([rowspan]):nth-child(10):nth-last-child(2) + TD:not([colspan]):not([rowspan]):nth-child(11):nth-last-child(1)"}}, [RowSelector="TABLE.sticky-header-multi.sortable.wikitable > * > TR"]),
    #"En-têtes promus" = Table.PromoteHeaders(#"Table extraite à partir de code Html", [PromoteAllScalars=true]),
    #"Type modifié" = Table.TransformColumnTypes(#"En-têtes promus",{{"Agglomération", type text}, {"Pays", type text}, {"Population selon l'ONU(2018)[12]", Int64.Type}, {"Ville[note 1]", type text}, {"Ville[note 1]_1", type text}, {"Ville[note 1]_2", type text}, {"", type text}, {"Zone urbaine[8]", type text}, {"Zone urbaine[8]_3", type text}, {"Aire urbaine", type text}, {"Aire urbaine_4", type text}}),
    #"En-têtes promus1" = Table.PromoteHeaders(#"Type modifié", [PromoteAllScalars=true]),
    #"Type modifié1" = Table.TransformColumnTypes(#"En-têtes promus1",{{"Column1", type text}, {"Column2", type text}, {"Column3", Int64.Type}, {"Statut administratif", type text}, {"Population", type text}, {"Surfacekm2", type text}, {"Densité par km²", Int64.Type}, {"Population_1", type text}, {"Surfacekm2_2", type text}, {"Population_3", type text}, {"Surfacekm2_4", type text}}),
    #"Lignes groupées" = Table.Group(#"Type modifié1", {"Statut administratif"}, {{"Nombre de villes de ce statut", each Table.RowCount(_), Int64.Type}})
in
    #"Lignes groupées"